name: Publish Tagged Commit to PyPI 

on:
  pull_request:
    branches:
      - '*'
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'master'


jobs:
  build-n-publish:
    name: Build and publish Python Package
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"

      - name: Setup Ghidra
        run: |
          wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0_build/ghidra_10.0_PUBLIC_20210621.zip --output-document=ghidra.zip
          unzip ghidra.zip

      - name: Prepare Jython Environment
        run:
          pip2.7 install --target="$(pwd)/ghidra_10.0_PUBLIC/Ghidra/Features/Python/data/jython-2.7.2/Lib/site-packages" attrs typing

      - name: Build Package
        run: |
          "$(pwd)/ghidra_10.0_PUBLIC/support/analyzeHeadless" /tmp tmp -scriptPath $(pwd) -preScript generate_ghidra_pyi.py ./ ${GITHUB_REF#refs/*/v}
          test -f setup.py # check manually, because analyzeHeadless doesn't fail on script failure
          test -d ghidra-stubs

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          wheel
          --user

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py bdist_wheel --universal
          python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: stubs
          path: ./dist/*


      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith('refs/tags/v', github.ref) }}
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
